# generate Tensor

In [4]:
import torch

In [6]:
# create a torch.Tensor object with data
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

M_data = [[1, 2, 3], [4, 5, 6]]
M = torch.Tensor(M_data)
print(M)

T_data = [[[1,2], [3,4]],
          [[5,6], [7,8]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [7]:
# torch.ones
a = torch.ones(3)
print(a)

b = torch.ones(2, 3)
print(b)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# torch.zeros
a = torch.zeros(4)
print(a)

b = torch.zeros(3, 2, 4)
print(b)

tensor([0., 0., 0., 0.])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [11]:
# 초기화하면서 현재 메모리에 존재하는 값
x = torch.empty(5,3)
print(x)

# 랜덤 숫자로 채움
x = torch.rand(5, 3)
print(x)

x = torch.rand(4, dtype=torch.double)
print(x)

x = torch.rand(2, 3, dtype=torch.float)
print(x)

tensor([[-2.1298e-28,  3.0796e-41,  4.4842e-44],
        [ 0.0000e+00,         nan,  1.5554e-43],
        [ 1.0948e+21,  9.2868e-04,  1.3556e-19],
        [ 9.8864e-33,  1.0008e+01,  2.5591e-41],
        [ 1.5414e-43,  1.4013e-43,  0.0000e+00]])
tensor([[0.1072, 0.2580, 0.9500],
        [0.8993, 0.8939, 0.0376],
        [0.0974, 0.5003, 0.7446],
        [0.9263, 0.6281, 0.7114],
        [0.8272, 0.1111, 0.9354]])
tensor([0.4887, 0.5681, 0.8466, 0.8001], dtype=torch.float64)
tensor([[0.9912, 0.9881, 0.2391],
        [0.8538, 0.8282, 0.2174]])


In [12]:
# size
print(x.size())

torch.Size([2, 3])


# Indexing Tensor

In [15]:
temp = torch.Tensor([0, 1, 2, 3, 4, 5 ,6 ,7])

print(temp[1:4])
print(temp[1:7:2])

tensor([1., 2., 3.])
tensor([1., 3., 5.])


In [18]:
temp = torch.Tensor([[1,2,3],[4,5,6]])

print(temp)
print(temp[1:])
print(temp[1:, 1:])
print(temp[:, 0])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[4., 5., 6.]])
tensor([[5., 6.]])
tensor([1., 4.])


# Tensor element types

In [19]:
float_points = torch.ones(5,2, dtype=torch.float32)
int_points = torch.zeros(3, dtype=torch.int64)

print(float_points)
print(int_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([0, 0, 0])


In [21]:
default_points = torch.Tensor([2,2])
print(default_points)

tensor([2., 2.])


In [22]:
# find out type
print(float_points.dtype)
print(int_points.dtype)
print(default_points.dtype)

torch.float32
torch.int64
torch.float32


In [24]:
# change dtype in specific
to_int = float_points.int()
print(to_int.dtype)

# using 'to'
to_int_2 = float_points.to(torch.int64)
print(to_int_2.dtype)

to_float = int_points.to(torch.float16)
print(to_float.dtype)

torch.int32
torch.int64
torch.float16


# Tensor Shape and Reshape

In [25]:
a = torch.Tensor([[1,2,3],[4,5,6]])

print(a)
print(a.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [26]:
# size
print(a.size())

torch.Size([2, 3])


In [27]:
# reshape
a_reshape = a.reshape(3,2)
print(a_reshape)

a_reshape = a.reshape(-1,2)
print(a_reshape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [28]:
# if shape is not compatible with the current shape -> ERROR
a_reshape = a.reshape(4,2)
print(a_reshape)

RuntimeError: ignored

In [31]:
# view : 원본 input과 동일한 저장이 필요할 경우
x = torch.randn(4,4)
print(x)
print(x.size(),'\n')

y = x.view(16)
print(y)
print(y.size(),'\n')

z = x.view(-1,8)
print(z)
print(z.size(),'\n')

tensor([[ 0.8582, -0.6810, -0.8377,  0.5846],
        [-1.5790, -1.0830,  1.2445,  0.0465],
        [ 0.1097,  0.1523,  1.2564,  0.2377],
        [-0.5357,  0.7247, -0.0541,  0.3091]])
torch.Size([4, 4]) 

tensor([ 0.8582, -0.6810, -0.8377,  0.5846, -1.5790, -1.0830,  1.2445,  0.0465,
         0.1097,  0.1523,  1.2564,  0.2377, -0.5357,  0.7247, -0.0541,  0.3091])
torch.Size([16]) 

tensor([[ 0.8582, -0.6810, -0.8377,  0.5846, -1.5790, -1.0830,  1.2445,  0.0465],
        [ 0.1097,  0.1523,  1.2564,  0.2377, -0.5357,  0.7247, -0.0541,  0.3091]])
torch.Size([2, 8]) 



# Transpose

In [33]:
x = torch.randn(3)
print(x)
print(torch.t(x),'\n')

y = torch.randn(2,3)
print(y)
print(torch.t(y))

tensor([-0.9715, -0.9621,  1.5561])
tensor([-0.9715, -0.9621,  1.5561]) 

tensor([[ 0.0076,  1.3555, -0.0995],
        [-0.4884, -0.0528,  0.7061]])
tensor([[ 0.0076, -0.4884],
        [ 1.3555, -0.0528],
        [-0.0995,  0.7061]])


In [38]:
a = torch.randn(2, 3)
print(a)
print(torch.transpose(a, 0, 1))

tensor([[ 1.2121,  0.5437, -0.6126],
        [ 1.0001, -1.5410, -0.0291]])
tensor([[ 1.2121,  1.0001],
        [ 0.5437, -1.5410],
        [-0.6126, -0.0291]])


In [39]:
# complex case
ex = torch.randn(64, 128, 728)
print(ex.shape)
transposed = torch.transpose(ex, 1, 2)
print(transposed.shape)

torch.Size([64, 128, 728])
torch.Size([64, 728, 128])


# Operation

In [40]:
x = torch.ones(1, 2)
y = torch.ones(5, 2)
print(y)
#
print(x+y)
#
print(torch.add(x,y))
#
result = torch.empty(5, 2)
torch.add(x, y, out=result)
print(result)
#
print(y.add_(x))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])


# Numpy interpretability

In [2]:
import torch

points = torch.ones(3, 4)
points_np = points.numpy()

print(points_np)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
type(points_np)

numpy.ndarray

In [5]:
points = torch.from_numpy(points_np)
print(points)
type(points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


torch.Tensor