# **Vector Operations**

## Dot Product

In [1]:
import numpy as np

u = np.random.uniform(0, 5, (4, ))
v = np.random.uniform(0, 5, (4, ))

sum_hadamard = np.sum(u*v)
np_dot = np.dot(u, v)

print("sum_hadamard :", sum_hadamard )
print("np_dot: ", np_dot)

sum_hadamard : 15.54822835363401
np_dot:  15.54822835363401


## Operations of a Artificial Neuron

In [3]:
import numpy as np

x = np.random.uniform(0, 5, (4, ))

w = np.random.uniform(0, 5, (4, ))
b = np.random.uniform(0, 5, ())

affine = np.dot(x, w) + b
activation = 1/(1 + np.exp(-affine))

## Matrix-vector Multiplication

In [4]:
import numpy as np

M = np.random.uniform(0, 5, (3, 4))
u = np.random.uniform(0, 5, (4, ))

mat_vec_mul = np.empty((3, ))
for row_idx, row in enumerate(M):
  mat_vec_mul[row_idx] = np.dot(row, u)

np_matmul = np.matmul(M, u)

print("mat_vec_mul: \n", mat_vec_mul)
print("np_matmul: \n", np_matmul)

mat_vec_mul: 
 [27.41381293 41.52761369 41.92757072]
np_matmul: 
 [27.41381293 41.52761369 41.92757072]


In [6]:
import numpy as np

M = np.random.uniform(0, 5, (3, 4))
N = np.random.uniform(0, 5, (4, 5))

mat_mat_mul = np.empty((3, 5))

for M_row_idx in range(3):
  for N_col_idx in range(5):
    dot_prod = np.dot(M[M_row_idx, :], N[:, N_col_idx] )
    mat_mat_mul[M_row_idx, N_col_idx] = dot_prod

np_matmul = np.matmul(M, N)

print("mat_mat_mul: \n",mat_mat_mul)
print("np_matmul: \n",np_matmul)

mat_mat_mul: 
 [[34.70153911 27.11831441 34.38599156 22.12614908 23.25064444]
 [25.04725569 18.39682887 23.43186268 16.7104643  16.83711773]
 [41.86294656 30.18746678 31.91045107 30.67152412 34.96842028]]
np_matmul: 
 [[34.70153911 27.11831441 34.38599156 22.12614908 23.25064444]
 [25.04725569 18.39682887 23.43186268 16.7104643  16.83711773]
 [41.86294656 30.18746678 31.91045107 30.67152412 34.96842028]]


## Operations of Artificial Neuron

In [8]:
import numpy as np

x = np.random.uniform(0, 5, (3, 4))

w = np.random.uniform(0, 5, (4, 5))
b = np.random.uniform(0, 5, (5, ))

affine = np.matmul(x, w) + b
print(affine.shape)
activation = 1 / (1 + np.exp(-affine))

(3, 5)
