# **Merging Row/Column-wise**

## np.hstack and np.vstack

In [3]:
import numpy as np

a = np.random.randint(0, 10, (4, ))
b = np.random.randint(0, 10, (4, ))

print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

vstack = np.vstack([a, b])
hstack = np.hstack([a, b])

print("vstack\n", vstack)
print("hstack\n", hstack) # shape (8,)

a: (4,)
[2 2 7 8]
b: (4,)
[5 0 5 3]

vstack
 [[2 2 7 8]
 [5 0 5 3]]
hstack
 [2 2 7 8 5 0 5 3]


In [4]:
import numpy as np

a = np.random.randint(0, 10, (1, 3))
b = np.random.randint(0, 10, (1, 3))

print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

vstack = np.vstack((a,b))
hstack = np.hstack([a, b])

print("vstack\n", vstack)
print("hstack\n", hstack)  # shape (1, 6)

a: (1, 3)
[[4 7 0]]
b: (1, 3)
[[4 9 1]]

vstack
 [[4 7 0]
 [4 9 1]]
hstack
 [[4 7 0 4 9 1]]


In [7]:
import numpy as np

a = np.random.randint(0, 10, (3, 1))
b = np.random.randint(0, 10, (3, 1))

print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

vstack = np.vstack((a,b))
hstack = np.hstack((a, b))

print("vstack\n", vstack)
print("hstack\n", hstack) 

a: (3, 1)
[[5]
 [4]
 [0]]
b: (3, 1)
[[7]
 [8]
 [4]]

vstack
 [[5]
 [4]
 [0]
 [7]
 [8]
 [4]]
hstack
 [[5 7]
 [4 8]
 [0 4]]


In [10]:
import numpy as np

a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (4, ))

print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

vstack = np.vstack([a,b])
print(f"vstack: {vstack.shape}\n", vstack)

a: (3, 4)
[[2 9 3 0]
 [0 6 7 4]
 [2 4 1 2]]
b: (4,)
[6 9 3 8]

vstack: (4, 4)
 [[2 9 3 0]
 [0 6 7 4]
 [2 4 1 2]
 [6 9 3 8]]


행렬을 갖고있는데 새로운 데이터를 오른쪽에 쌓고 싶다.<br/> 그러나 새로운 데이터가 **벡터 케이스**일때는 오류가 난다.

In [11]:
import numpy as np

a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (3, ))

print(f"a: {a.shape}\n{a}")
print(f"b: {b.shape}\n{b}\n")

hstack = np.hstack([a,b])
print(f"hstack: {hstack.shape}\n", hstack)

a: (3, 4)
[[9 5 6 2]
 [7 7 3 0]
 [7 3 4 5]]
b: (3,)
[6 4 1]



ValueError: ignored

In [12]:
hstack = np.hstack([a, b.reshape((-1, 1))])
print(f"hstack: {hstack.shape}\n", hstack)

hstack: (3, 5)
 [[9 5 6 2 6]
 [7 7 3 0 4]
 [7 3 4 5 1]]


## Making Toy Datasets

In [16]:
import numpy as np

dataset = np.empty((0,4)) # 빈 공간을 잡아둠
print("initial shape: ", dataset.shape)

for iter in range(5):
  data_sample = np.random.uniform(0, 5, (1, 4))
  dataset = np.vstack((dataset, data_sample))
  print(f"iter/shape: {iter}/{dataset.shape}")

print('\n',dataset)

initial shape:  (0, 4)
iter/shape: 0/(1, 4)
iter/shape: 1/(2, 4)
iter/shape: 2/(3, 4)
iter/shape: 3/(4, 4)
iter/shape: 4/(5, 4)

 [[3.24097616 1.7950649  0.89064655 3.41195424]
 [4.86036094 3.4613756  4.01945124 0.37239339]
 [2.22428365 1.21810581 1.24331952 2.0178848 ]
 [4.55148337 1.94039853 0.80118371 2.67440826]
 [3.83429879 2.94822109 2.14893862 1.1452472 ]]


In [19]:
import numpy as np

dataset = np.empty((4,0)) # 빈 공간을 잡아둠
print("initial shape: ", dataset.shape)

for iter in range(5):
  data_sample = np.random.uniform(0, 5, (4, 1))
  dataset = np.hstack((dataset, data_sample))
  print(f"iter/shape: {iter}/{dataset.shape}")

print('\n',dataset)

initial shape:  (4, 0)
iter/shape: 0/(4, 1)
iter/shape: 1/(4, 2)
iter/shape: 2/(4, 3)
iter/shape: 3/(4, 4)
iter/shape: 4/(4, 5)

 [[0.30409195 0.8417344  4.44981837 0.44144914 3.64494521]
 [0.06438091 4.00502339 3.20124093 1.21830696 2.92143659]
 [3.94278527 1.61788383 1.12783385 2.89201046 3.36374354]
 [1.00595625 2.48501856 2.98699086 4.24946038 3.86502117]]


## Making Toy Datasets in **Efficient Way**

In [20]:
import numpy as np

a = np.random.randint(0, 10, (1, 4))
b = np.random.randint(0, 10, (1, 4)) 
c = np.random.randint(0, 10, (1, 4))

arr_list = [a, b, c]
vstack = np.vstack(arr_list)

print(vstack)

[[2 6 1 6]
 [9 6 6 4]
 [9 6 0 0]]


In [21]:
import numpy as np

dataset_tmp = list() # 1. 먼저 빈 리스트 생성
for iter in range(100):
  data_sample = np.random.uniform(0, 5, (1, 4))
  dataset_tmp.append(data_sample)  # 2. append로 빈 리스트에 넣기

dataset = np.vstack(dataset_tmp) # 3. 한번에 vstack으로 합치기

print(dataset.shape)

(100, 4)


# **Merging ndarrays using np.concatenate**

## np.concatenate

In [22]:
import numpy as np

a = np.random.randint(0, 10, (3, ))
b = np.random.randint(0, 10, (4, ))

concat = np.concatenate([a, b])
concat0 = np.concatenate([a, b], axis=0)

print(f"a: {a.shape}\n {a}")
print(f"b: {b.shape}\n {b}\n")

print(f"concat.shape: {concat.shape}\n {concat}")
print(f"concat0.shape: {concat0.shape}\n {concat0}")

a: (3,)
 [1 8 2]
b: (4,)
 [3 8 5 5]

concat.shape: (7,)
 [1 8 2 3 8 5 5]
concat0.shape: (7,)
 [1 8 2 3 8 5 5]


In [24]:
import numpy as np

a = np.random.randint(0, 10, (3, ))
b = np.random.randint(0, 10, (4, ))
c = np.random.randint(0, 10, (5, )) 

concat = np.concatenate([a, b, c])

print(f"a: {a.shape}\n {a}")
print(f"b: {b.shape}\n {b}")
print(f"c: {c.shape}\n {c}\n")

print(f"concat.shape: {concat.shape}\n {concat}")

a: (3,)
 [6 8 3]
b: (4,)
 [5 2 4 4]
c: (5,)
 [2 9 3 0 8]

concat.shape: (12,)
 [6 8 3 5 2 4 4 2 9 3 0 8]


In [26]:
import numpy as np

a = np.random.randint(0, 10, (1, 3))
b = np.random.randint(0, 10, (1, 3))

axis0 = np.concatenate([a, b], axis=0)
axis1 = np.concatenate([a, b], axis=1)  # np.hstack
axis_n1 = np.concatenate([a, b], axis=-1)

print(f"a: {a.shape}\n {a}")
print(f"b: {b.shape}\n {b}\n")

print(f"axis0.shape: {axis0.shape}\n {axis0}")
print(f"axis1.shape: {axis1.shape}\n {axis1}")
print(f"axis_n1.shape: {axis_n1.shape}\n {axis_n1}")

a: (1, 3)
 [[9 9 5]]
b: (1, 3)
 [[8 0 0]]

axis0.shape: (2, 3)
 [[9 9 5]
 [8 0 0]]
axis1.shape: (1, 6)
 [[9 9 5 8 0 0]]
axis_n1.shape: (1, 6)
 [[9 9 5 8 0 0]]


In [27]:
import numpy as np

a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (3, 2))

concat = np.concatenate([a, b], axis=1) 

a = np.random.randint(0, 10, (1, 3))
b = np.random.randint(0, 10, (1, 3))

print(f"concat.shape: {concat.shape}\n {concat}")

concat.shape: (3, 6)
 [[2 8 6 7 0 7]
 [1 4 3 5 6 1]
 [3 6 7 4 2 5]]


In [29]:
import numpy as np

a = np.random.randint(0, 10, (3, 4, 5))
b = np.random.randint(0, 10, (10, 4, 5))  

concat0 = np.concatenate([a, b], axis=0) # 4, 5가 동일하므로 axis=0으로 합칠 수 있다.
print(f"concat0.shape: {concat0.shape}")

concat0.shape: (13, 4, 5)


In [30]:
import numpy as np

a = np.random.randint(0, 10, (3, 4, 5))
b = np.random.randint(0, 10, (3, 10, 5))  

concat1 = np.concatenate([a, b], axis=1) # 3, 5가 동일하므로 axis=1으로 합칠 수 있다.
print(f"concat1.shape: {concat1.shape}")

concat1.shape: (3, 14, 5)


In [31]:
import numpy as np

a = np.random.randint(0, 10, (3, 4, 5))
b = np.random.randint(0, 10, (3, 4, 10))  

concat2 = np.concatenate([a, b], axis=2) # 3, 4가 동일하므로 axis=2으로 합칠 수 있다.
print(f"concat2.shape: {concat2.shape}")

concat2.shape: (3, 4, 15)


## Making Toy Datasets

In [32]:
import numpy as np

dataset_tmp = list()
for iter in range(100):
  data_sample = np.random.uniform(0, 5, (1, 4))
  dataset_tmp.append(data_sample)

concat = np.concatenate(dataset_tmp, axis=0)
print(concat.shape)

(100, 4)


In [33]:
import numpy as np

dataset_tmp = list()
for iter in range(100):
  data_sample = np.random.uniform(0, 5, (4, 1))
  dataset_tmp.append(data_sample)

concat = np.concatenate(dataset_tmp, axis=1)
print(concat.shape)

(4, 100)


## np.dstack

새로운 디멘션을 만드면서 합쳐짐

In [34]:
import numpy as np

R = np.random.randint(0, 10, (100, 200))
G = np.random.randint(0, 10, size=R.shape)
B = np.random.randint(0, 10, size=R.shape)

image = np.dstack([R, G, B])
print(image.shape)

(100, 200, 3)


In [36]:
import numpy as np

R = np.random.randint(0, 10, (100, 200, 3))
G = np.random.randint(0, 10, size=R.shape)
B = np.random.randint(0, 10, size=R.shape)

image = np.dstack([R, G, B])
print(image.shape)

(100, 200, 9)


## np.stack

In [37]:
import numpy as np

a = np.random.randint(0, 10, (100, 200))
b = np.random.randint(0, 10, (100, 200))
c = np.random.randint(0, 10, (100, 200))

print("ndim==2: ", np.stack([a,b,c]).shape)

ndim==2:  (3, 100, 200)


In [39]:
import numpy as np

a = np.random.randint(0, 10, (100, 200, 300))
b = np.random.randint(0, 10, (100, 200, 300))
c = np.random.randint(0, 10, (100, 200, 300))

print("ndim==3: ", np.stack([a,b,c]).shape)

ndim==3:  (3, 100, 200, 300)


In [41]:
import numpy as np

a = np.random.randint(0, 10, (100, 200, 300))
b = np.random.randint(0, 10, (100, 200, 300))
c = np.random.randint(0, 10, (100, 200, 300))

print("axis=0: ", np.stack([a,b,c], axis=0).shape)

print("axis=1: ", np.stack([a,b,c], axis=1).shape)

print("axis=2: ", np.stack([a,b,c], axis=2).shape)

print("axis=3: ", np.stack([a,b,c], axis=3).shape)

axis=0:  (3, 100, 200, 300)
axis=1:  (100, 3, 200, 300)
axis=2:  (100, 200, 3, 300)
axis=3:  (100, 200, 300, 3)


hstack, vstack, dstack : 행렬을 다루는데 많이 사용<br/>
concatenate, stack: 고차원을 다루는데 많이 사용