# **Rounding Functions**

## Rounding Functions

In [2]:
import numpy as np

x = np.random.uniform(-5, 5, (5, ))

np_around = np.around(x, decimals=2)
np_round_ = np.round_(x, decimals=2)
x_round = x.round(decimals=2)

print(f"x: \n{x}\n")

print(f"np_around: \n{np_around}")
print(f"np_round_: \n{np_round_}")
print(f"x_round: \n{x_round}")

x: 
[-4.35131287 -1.63911151 -0.25040073  3.03450672  4.99364981]

np_around: 
[-4.35 -1.64 -0.25  3.03  4.99]
np_round_: 
[-4.35 -1.64 -0.25  3.03  4.99]
x_round: 
[-4.35 -1.64 -0.25  3.03  4.99]


## Ceiling and Flooring Functions

In [3]:
import numpy as np

x = np.random.uniform(-5, 5, (5, ))

ceil = np.ceil(x)
floor = np.floor(x)

print(f"x: \n{x}\n")

print(f"ceil: \n{ceil}")
print(f"floor: \n{floor}")

x: 
[ 1.51563593 -4.7885415  -4.12017195  1.81689459 -3.34616301]

ceil: 
[ 2. -4. -4.  2. -3.]
floor: 
[ 1. -5. -5.  1. -4.]


## Truncation Functions

In [4]:
import numpy as np

x = np.random.uniform(-5, 5, (5, ))

trunc = np.trunc(x)

print(f"x: \n{x}\n")

print(f"trunc: \n{trunc}")

x: 
[ 1.86112722 -3.86253639  2.05010698  2.92102588  0.47103088]

trunc: 
[ 1. -3.  2.  2.  0.]


where을 통한 trunc 구현

In [5]:
trunc_where = np.where(x >=0, np.floor(x), np.ceil(x))

print(f"x: \n{x}\n")

print(f"trunc_where: \n{trunc_where}")

x: 
[ 1.86112722 -3.86253639  2.05010698  2.92102588  0.47103088]

trunc_where: 
[ 1. -3.  2.  2.  0.]


In [6]:
import numpy as np

x = np.random.uniform(-5, 5, (5, ))

trunc = 0.1*np.trunc(10*x) # 소수점 첫째자리까지
# 3.723 -> 37.23 에서 flooring되면 37이 되고 0.1이 곱해져서 3.7이 됨

print(f"x: \n{x}\n")

print(f"trunc: \n{trunc}")

x: 
[-3.32427886 -4.80593577  3.61955421 -2.20850847 -2.902842  ]

trunc: 
[-3.3 -4.8  3.6 -2.2 -2.9]


In [8]:
import numpy as np

x = np.random.uniform(-5, 5, (5, ))

int_part = np.trunc(x)
frac_part = x - int_part

print(f"x: \n{x}\n")

print(f"int_part: \n{int_part}")
print(f"frac_part: \n{frac_part}")

x: 
[ 0.5518718  -2.66242365 -4.50283348 -3.00638915  3.5353966 ]

int_part: 
[ 0. -2. -4. -3.  3.]
frac_part: 
[ 0.5518718  -0.66242365 -0.50283348 -0.00638915  0.5353966 ]


# **Sorting Functions**

## Sorting Vectors

In [9]:
import numpy as np

x = np.random.randint(0, 100 ,(10, ))

sort = np.sort(x)
argsort = np.argsort(x)

print(f"x: \n{x}\n")

print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}")

x: 
[43 18 85 62 21 59 90 13 36 63]

sort: 
[13 18 21 36 43 59 62 63 85 90]
argsort: 
[7 1 4 8 0 5 3 9 2 6]


In [10]:
import numpy as np

x = np.random.randint(0, 100 ,(10, ))

sort = np.sort(x)[::-1]
argsort = np.argsort(x)[::-1]

print(f"x: \n{x}\n")

print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}")

x: 
[16 28 16 31 44 44  2 84 19 49]

sort: 
[84 49 44 44 31 28 19 16 16  2]
argsort: 
[7 9 5 4 3 1 8 2 0 6]


In [11]:
import numpy as np

pred = np.random.uniform(0, 100, (5, ))
pred /= pred.sum()

top3_pred = np.sort(pred)[::-1][:3]
top3_indices = np.argsort(pred)[::-1][:3]

print(f"pred: \n{pred}\n")

print(f"top3_pred: \n{top3_pred}")
print(f"top3_indices: \n{top3_indices}")

pred: 
[0.20318344 0.27416003 0.23968269 0.28189296 0.00108089]

top3_pred: 
[0.28189296 0.27416003 0.23968269]
top3_indices: 
[3 1 2]


## Sorting Matrices

In [13]:
import numpy as np

x = np.random.randint(0, 100 ,(4, 5))

sort = np.sort(x, axis=0)
argsort = np.argsort(x, axis=0)

print(f"x: \n{x}\n")

print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}")

x: 
[[46 29 69 80 44]
 [72 42 17 71 85]
 [27 53 29 84 56]
 [97 17  6 30 76]]

sort: 
[[27 17  6 30 44]
 [46 29 17 71 56]
 [72 42 29 80 76]
 [97 53 69 84 85]]
argsort: 
[[2 3 3 3 0]
 [0 0 1 1 2]
 [1 1 2 0 3]
 [3 2 0 2 1]]


In [16]:
import numpy as np

x = np.random.randint(0, 100 ,(4,5))

sort = np.sort(x, axis=0)[::-1, :]
argsort = np.argsort(x, axis=0)[::-1, :]

print(f"x: \n{x}\n")

print(f"sort: \n{sort}")
print(f"argsort: \n{argsort}")

x: 
[[13 30 40 43 66]
 [ 2 37 87 70 56]
 [11 12 72 21 64]
 [93 52 52  5  2]]

sort: 
[[93 52 87 70 66]
 [13 37 72 43 64]
 [11 30 52 21 56]
 [ 2 12 40  5  2]]
argsort: 
[[3 3 1 1 0]
 [0 1 2 0 2]
 [2 0 3 2 1]
 [1 2 0 3 3]]


In [18]:
import numpy as np

scores = np.random.randint(0, 100 ,(4,5))

sort = np.sort(scores, axis=0)[::-1, :]
argsort = np.argsort(scores, axis=0)[::-1, :]

top2_scores = sort[:2, :]
top2_students = argsort[:2, :]

print(f"scores: \n{scores}\n")

print(f"top2_scores: \n{top2_scores}")
print(f"top2_students: \n{top2_students}")

scores: 
[[93 24 80 14 55]
 [53 13 95 47 85]
 [ 3 91 12 71  6]
 [86 26 75  6 18]]

top2_scores: 
[[93 91 95 71 85]
 [86 26 80 47 55]]
top2_students: 
[[0 2 1 2 1]
 [3 3 0 1 0]]


In [20]:
import numpy as np

x = np.random.randint(0, 100, (4,5))

sort_ascending = np.sort(x, axis=1)
argsort_ascending = np.argsort(x, axis=1)

sort_descending = np.sort(x, axis=1)[: , ::-1]
argsort_descending = np.argsort(x, axis=1)[:, ::-1]

print(f"x: \n{x}\n")

print(f"sort_ascending: \n{sort_ascending}")
print(f"argsort_ascending: \n{argsort_ascending}\n")

print(f"sort_descending: \n{sort_descending}")
print(f"argsort_descending: \n{argsort_descending}")

x: 
[[31 32 48 81 44]
 [76  9 26 48 69]
 [68 60 90 77 17]
 [ 4  0 52 26 67]]

sort_ascending: 
[[31 32 44 48 81]
 [ 9 26 48 69 76]
 [17 60 68 77 90]
 [ 0  4 26 52 67]]
argsort_ascending: 
[[0 1 4 2 3]
 [1 2 3 4 0]
 [4 1 0 3 2]
 [1 0 3 2 4]]

sort_descending: 
[[81 48 44 32 31]
 [76 69 48 26  9]
 [90 77 68 60 17]
 [67 52 26  4  0]]
argsort_descending: 
[[3 2 4 1 0]
 [0 4 3 2 1]
 [2 3 0 1 4]
 [4 2 3 0 1]]


In [21]:
import numpy as np

scores = np.random.randint(0, 100, (5, 3))

sort = np.sort(scores, axis=1)
argsort = np.argsort(scores, axis=1)

bottom2_scores = sort[: , :2]
bottom2_subjects = argsort[:, :2]

print(f"scores: \n{scores}\n")

print(f"bottom2_scores: \n{bottom2_scores}")
print(f"bottom2_subjects: \n{bottom2_subjects}")

scores: 
[[28 91 50]
 [44 95 53]
 [87 91  8]
 [50 36 23]
 [40 65 68]]

bottom2_scores: 
[[28 50]
 [44 53]
 [ 8 87]
 [23 36]
 [40 65]]
bottom2_subjects: 
[[0 2]
 [0 2]
 [2 0]
 [2 1]
 [0 1]]
