# **Sum, Prod, and Diff**

## Summation

**cumsum**

1차원

In [1]:
import numpy as np

a = np.arange(5)
print("ndarray: ",a)

# 누적 합
cumsum = np.cumsum(a)
print("cumsum: ", cumsum)

ndarray:  [0 1 2 3 4]
cumsum:  [ 0  1  3  6 10]


2차원

In [3]:
import numpy as np

a = np.arange(3*3).reshape((3,3))
print("ndarray: {}\n{}".format(a.shape, a))

cumsum = np.cumsum(a)
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))

ndarray: (3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
cumsum: (9,)
[ 0  1  3  6 10 15 21 28 36]


In [4]:
cumsum = np.cumsum(a).reshape((a.shape))
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))

cumsum: (3, 3)
[[ 0  1  3]
 [ 6 10 15]
 [21 28 36]]


3차원

In [6]:
import numpy as np

a = np.arange(2*3*4).reshape((2,3,4))
print("ndarray: {}\n{}".format(a.shape, a))

cumsum = np.cumsum(a)
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))

ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
cumsum: (24,)
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190 210 231 253 276]


In [7]:
cumsum = np.cumsum(a).reshape((a.shape))
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))

cumsum: (2, 3, 4)
[[[  0   1   3   6]
  [ 10  15  21  28]
  [ 36  45  55  66]]

 [[ 78  91 105 120]
  [136 153 171 190]
  [210 231 253 276]]]


cumsum(axis=0/1) axis argument 추가

In [8]:
import numpy as np

a = np.arange(3*4).reshape((3,4))
print("ndarray: {}\n{}".format(a.shape, a))

cumsum = np.cumsum(a, axis=0)
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))

ndarray: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
cumsum: (3, 4)
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [9]:
cumsum = np.cumsum(a, axis=1)
print("cumsum: {}\n{}".format(cumsum.shape, cumsum))

cumsum: (3, 4)
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


## Product

In [13]:
import numpy as np

a = np.arange(1,5)
print("ndarray: ",a)

prod = np.prod(a)
cumprod = np.cumprod(a)

print("prod: {}\n{}".format(prod.shape, prod))
print("cumprod: {}\n{}".format(cumprod.shape, cumprod))

ndarray:  [1 2 3 4]
prod: ()
24
cumprod: (4,)
[ 1  2  6 24]


In [14]:
# [::-1]
cumprod = np.cumprod(a)[::-1]

print("cumprod: {}\n{}".format(cumprod.shape, cumprod))

cumprod: (4,)
[24  6  2  1]


In [16]:
import numpy as np

a = np.arange(1, 1+12).reshape((3,-1))
print("ndarray: {}\n{}".format(a.shape, a))

prod = np.prod(a, axis=0)
cumprod = np.cumprod(a, axis=0)

print("prod: {}\n{}".format(prod.shape, prod))
print("cumprod: {}\n{}".format(cumprod.shape, cumprod))

ndarray: (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
prod: (4,)
[ 45 120 231 384]
cumprod: (3, 4)
[[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]]


## Difference

In [17]:
import numpy as np

a = np.random.randint(0, 10, (5, ))
print("ndarray: {}\n{}".format(a.shape, a))

diff = np.diff(a)
print("diff: {}\n{}".format(diff.shape, diff))

ndarray: (5,)
[9 2 8 0 4]
diff: (4,)
[-7  6 -8  4]


## Differentiation of Discrete-time Signal

In [18]:
import numpy as np
np.random.seed(0)

a = np.random.randint(0, 10, (4, 4))
print("ndarray: {}\n{}".format(a.shape, a))

diff = np.diff(a, axis=0)
print("diff: {}\n{}".format(diff.shape, diff))

ndarray: (4, 4)
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
diff: (3, 4)
[[ 2  9  0  2]
 [-5 -5  4  1]
 [ 6  4 -6  0]]


In [19]:
diff = np.diff(a, axis=1)
print("diff: {}\n{}".format(diff.shape, diff))

diff: (4, 3)
[[-5  3  0]
 [ 2 -6  2]
 [ 2  3 -1]
 [ 0 -7  5]]


# **Statistics**

## Mean and Median

mean 은 weight를 동일하게 설정한 1/n 이라고 생각

In [21]:
import numpy as np
np.random.seed(0)

x = np.random.randint(1, 10, (5,))
w = np.array([1, 2, 3, 4, 5])

print(np.average(x, weights=w))

print(np.sum(w*x)/np.sum(w))

5.066666666666666
5.066666666666666


홀수

In [22]:
import numpy as np

x = np.arange(9)
median = np.median(x)

print(x)
print(median)

[0 1 2 3 4 5 6 7 8]
4.0


짝수

In [23]:
import numpy as np

x = np.arange(10)
median = np.median(x)

print(x)
print(median)

[0 1 2 3 4 5 6 7 8 9]
4.5


In [24]:
import numpy as np

x = np.random.randint(1, 10, (100,))

mean = np.mean(x)
median = np.median(x)

print("mean/median: {} / {}".format(mean, median))

mean/median: 4.66 / 4.0


In [25]:
# 왜곡 
x = np.append(x, 1000)

mean = np.mean(x)
median = np.median(x)

print("mean/median: {} / {}".format(mean, median))

mean/median: 14.514851485148515 / 4.0


## Variance and Standard Deviation

In [26]:
import numpy as np

scores = np.random.normal(loc=10, scale=5, size=(100,))

var = scores.var()
std = scores.std()

print("variance: ", var)
print("standard deviation: ", std)

variance:  24.165158618655738
standard deviation:  4.915807016010264


In [28]:
print("square of std: ", std**2)
print("square of var:  ", var**0.5)

square of std:  24.165158618655738
square of var:   4.915807016010264


## Standardization

In [29]:
import numpy as np

means = [50,60,70] # 첫번째 컬럼 평균 50
stds = [3, 5, 10] # 첫번째 컬럼 표준편차 3
n_student, n_class = 100, 3

scores = np.random.normal(loc=means,
                          scale=stds,
                          size=(n_student, n_class))

print("shape of scores: ", scores.shape)
print("dtype of scores: ", scores.dtype)

shape of scores:  (100, 3)
dtype of scores:  float64


In [31]:
means = scores.mean(axis=0) # (100, 3)-> ( , 3) 이 되므로 과목별 평균이 구햐짐
stds = scores.std(axis=0)

print("means before stds: \n", means)
print("stds before stdz: \n", stds)

means befpre stds: 
 [49.84058606 60.19720968 70.57557423]
stds before stdz: 
 [ 3.08462727  4.92430961 11.31108828]


In [32]:
# standardization
score_stdz = (scores - means)/stds #(100,3) - (3,) / (3,) (3,)가 브로드캐스팅됨

means_stdz = score_stdz.mean(axis=0)
stds_stdz = score_stdz.std(axis=0)

print("means after stds: \n", means_stdz)
print("stds after stdz: \n", stds_stdz)

means after stds: 
 [-2.66453526e-15 -2.79165580e-15  7.10542736e-16]
stds after stdz: 
 [1. 1. 1.]


## Max Values and Indices

In [34]:
import numpy as np

a = np.random.randint(0, 100, (10, ))

M = np.max(a)
M_idx = np.argmax(a) # 최댓값의 인덱스

print("ndarray: ", a)
print("M / M_idx: {} / {}".format(M, M_idx))

ndarray:  [22 98 30 80 27 47 11 87 78 30]
M / M_idx: 98 / 1


In [37]:
import numpy as np

means = [50,60,70] # 첫번째 컬럼 평균 50
stds = [3, 5, 10] # 첫번째 컬럼 표준편차 3
n_student, n_class = 100, 3

scores = np.random.normal(loc=means,
                          scale=stds,
                          size=(n_student, n_class))
scores = scores.astype(np.float32)

scores_max = np.max(scores, axis=0)
scores_max_idx = np.argmax(scores, axis=0)

print("Max scores: ", scores_max)
print("Max indices: ", scores_max_idx)

Max scores:  [ 56.448723  70.11736  101.70975 ]
Max indices:  [14 70  0]


In [38]:
scores_max_idx = np.argmax(scores, axis=1) # 각 학생마다 최고점 과목
print("Max indices: ", scores_max_idx)

Max indices:  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 2
 2 2 1 2 2 2 2 2 2 2 2 1 1 1 1 2 2 2 2 2 2 2 2 1 2 2 2 2 1 2 1 1 1 2 2 1 1
 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2]


## Min - max Normalization

In [40]:
import numpy as np

means = [50,60,70] # 첫번째 컬럼 평균 50
stds = [3, 5, 10] # 첫번째 컬럼 표준편차 3
n_student, n_class = 100, 3

scores = np.random.normal(loc=means,
                          scale=stds,
                          size=(n_student, n_class))
scores = scores.astype(np.float32)

scores_max = np.max(scores, axis=0)
scores_min = np.min(scores, axis=0)

scores_mM_norm = (scores - scores_min) / (scores_max - scores_min)

scores_max = np.max(scores_mM_norm, axis=0)
scores_min = np.min(scores_mM_norm, axis=0)

print("Max scores: ", scores_max)
print("Min scores: ", scores_min)

Max scores:  [1. 1. 1.]
Min scores:  [0. 0. 0.]


## Maximum and Minimum

두 개의 array에 대해 최대 최소 

In [42]:
import numpy as np

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}")

maximum = np.maximum(u, v)
minimum = np.minimum(u, v)

print(f"maximum: {maximum.shape}\n{maximum}")
print(f"minimum: {minimum.shape}\n{minimum}")

u: (10,)
[8 3 9 9 9 6 4 9 3 4]
v: (10,)
[1 0 9 1 1 7 2 7 0 1]
maximum: (10,)
[8 3 9 9 9 7 4 9 3 4]
minimum: (10,)
[1 0 9 1 1 6 2 7 0 1]


In [43]:
import numpy as np

u = np.random.randint(0, 10, (3, 4))
v = np.random.randint(0, 10, (3, 4))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}")

maximum = np.maximum(u, v)
minimum = np.minimum(u, v)

print(f"maximum: {maximum.shape}\n{maximum}")
print(f"minimum: {minimum.shape}\n{minimum}")

u: (3, 4)
[[8 0 3 5]
 [1 2 1 4]
 [7 9 8 4]]
v: (3, 4)
[[4 6 5 1]
 [0 1 0 3]
 [5 5 6 9]]
maximum: (3, 4)
[[8 6 5 5]
 [1 2 1 4]
 [7 9 8 9]]
minimum: (3, 4)
[[4 0 3 1]
 [0 1 0 3]
 [5 5 6 4]]


## maximum, minimum api 직접 만들기

In [47]:
import numpy as np

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}\n")

maximum = np.zeros_like(u)
maximum[u >= v] = u[u >=v] 
maximum[u < v] = v[u < v]

print(f"np.maximum: {np.maximum(u,v)}")
print(f"maximum: {maximum}")

u: (10,)
[1 2 8 5 1 7 3 1 6 8]
v: (10,)
[2 7 8 9 6 9 8 5 0 0]

np.maximum: [2 7 8 9 6 9 8 5 6 8]
maximum: [2 7 8 9 6 9 8 5 6 8]


In [48]:
import numpy as np

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u: {u.shape}\n{u}")
print(f"v: {v.shape}\n{v}\n")

# u가 더 큰 부분은 100으로 v가 더 큰 부분은 -100으로
up_vals = np.full_like(u, fill_value=100)
down_vals = np.full_like(u, fill_value=-100)

print(np.where(u > v, up_vals, down_vals))

u: (10,)
[9 4 6 0 9 4 2 2 4 7]
v: (10,)
[1 9 6 4 6 8 6 9 2 7]

[ 100 -100 -100 -100  100 -100 -100 -100  100 -100]


In [53]:
maximum = np.maximum(u, v)
maximum_where = np.where(u > v, u, v)

print(f"maximum: {maximum.shape}\n{maximum}")
print(f"maximum(where): {maximum_where.shape}\n{maximum_where}")

maximum: (10,)
[9 9 6 4 9 8 6 9 4 7]
maximum(where): (10,)
[9 9 6 4 9 8 6 9 4 7]


In [55]:
minimum = np.minimum(u, v)
minimum_where = np.where(u > v, v, u)

print(f"minimum: {minimum.shape}\n{minimum}")
print(f"minimum(where): {minimum_where.shape}\n{minimum_where}")

minimum: (10,)
[1 4 6 0 6 4 2 2 2 7]
minimum(where): (10,)
[1 4 6 0 6 4 2 2 2 7]
