# 1-3: Activation Functions

## Code 1-3-1: Activation Layers

In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Activation
from tensorflow.math import exp, maximum

x = tf.random.normal(shape=(1,5))  # input setting

# imp. activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation(manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print("x: {}\n{}".format(x.shape, x.numpy()))

print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}\n".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}\n".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLU(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("ReLU(Manual): {}\n{}\n".format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[ 0.73901594  2.4190116   1.1552703  -0.59237367 -0.4674003 ]]
Sigmoid(Tensorflow): (1, 5)
[[0.6767806  0.9182656  0.7604722  0.35609043 0.38523173]]
Sigmoid(Manual): (1, 5)
[[0.67678064 0.91826564 0.76047224 0.3560904  0.38523176]]

Tanh(Tensorflow): (1, 5)
[[ 0.6285503   0.9842792   0.8194925  -0.5316006  -0.43609643]]
Tanh(Manual): (1, 5)
[[ 0.62855023  0.9842792   0.8194925  -0.5316007  -0.43609643]]

ReLU(Tensorflow): (1, 5)
[[0.73901594 2.4190116  1.1552703  0.         0.        ]]
ReLU(Manual): (1, 5)
[[0.73901594 2.4190116  1.1552703  0.         0.        ]]



## Code 1-3-2: Activation in Dense Layer

In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp

x = tf.random.normal(shape=(1,5))  # input setting

# imp. artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation(Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print('Artificial Neuron with Sigmoid: {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('Artificial Neuron with Tanh: {}\n{}'.format(y_tanh.shape, y_tanh.numpy()))
print('Artificial Neuron with ReLU: {}\n{}'.format(y_relu.shape, y_relu.numpy()))

# forward propagation(Manual)
print('\n====\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))
print("Activation value(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value(manual): {}\n{}".format(a.shape, a.numpy()))

Artificial Neuron with Sigmoid: (1, 1)
[[0.7388691]]
Artificial Neuron with Tanh: (1, 1)
[[0.8623343]]
Artificial Neuron with ReLU: (1, 1)
[[0.]]

====

Activation value(Tensorflow): (1, 1)
[[0.7388691]]
Activation value(manual): (1, 1)
[[0.7388691]]


# 1-4: Artificial Neurons

## Code 1-4-1: Artificial Neurons

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape=(1,10))  # input setting

dense = Dense(units=1, activation=activation)  # imp. affine function + activation

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B

if activation == 'sigmoid':
  y_man = 1/(1 + exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
  y_man = maximum(x, 0)

print("Activation: ", activation)
print("y_tf: {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man: {}\n{}\n".format(y_man.shape, y_man.numpy()))

Activation:  sigmoid
y_tf: (1, 1)
[[0.70479834]]

y_man: (1, 1)
[[0.70479834]]



# 1-5: Mininbatches

## Code 1-5-1: Shapes of Dense Layers

In [12]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # set input parmas
x = tf.random.normal(shape=(N, n_feature))  # generate minibatch

dense = Dense(units=1, activation='relu') # imp. an artificial Neuron
y = dense(x)  # forward propagation

W, B = dense.get_weights()  # get weight/bias

# print results
print("shape of x: {}".format(x.shape))
print("shape of W: {}".format(W.shape))
print("shape of B: {}".format(B.shape))

shape of x: (8, 10)
shape of W: (10, 1)
shape of B: (1,)


## Code 1-5-2: Output Calculations

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10  # set input params
x = tf.random.normal(shape=(N, n_feature))  # generate minibatch

dense = Dense(units=1, activation='sigmoid')  # imp. an artificial neuron
y_tf = dense(x)  # forward propagation(Tensorflow)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B  # forward propagation(manual)
y_man = 1 / (1 + exp(-y_man))

# print results
print("Output(Tensorflow): \n", y_tf.numpy())
print("Output(Manual): \n", y_man.numpy())

Output(Tensorflow): 
 [[0.75080633]
 [0.6434573 ]
 [0.64423746]
 [0.08597755]
 [0.19579414]
 [0.5114682 ]
 [0.12291831]
 [0.4087451 ]]
Output(Manual): 
 [[0.75080633]
 [0.6434573 ]
 [0.64423746]
 [0.08597758]
 [0.19579412]
 [0.51146823]
 [0.12291831]
 [0.40874514]]
