# 2-1: Dense Layers

## 2-1-1: Shapes of Dense Layers

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 1, 10
X = tf.random.normal(shape=(N, n_features))

n_neurons = 3
dense = Dense(units=n_neurons, activation='sigmoid')
Y = dense(X)

W,B = dense.get_weights()

print('==== Input/Weights/Bias====')
print('X: ', X.shape)
print('W: ', W.shape)
print('B: ', B.shape)
print('Y: ', Y.shape)

==== Input/Weights/Bias====
X:  (1, 10)
W:  (10, 3)
B:  (3,)
Y:  (1, 3)


In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 8, 10
X = tf.random.normal(shape=(N, n_features))

n_neurons = 3
dense = Dense(units=n_neurons, activation='sigmoid')
Y = dense(X)

W,B = dense.get_weights()

print('==== Input/Weights/Bias====')
print('X: ', X.shape)
print('W: ', W.shape)
print('B: ', B.shape)
print('Y: ', Y.shape)

==== Input/Weights/Bias====
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


## Code 2-1-2: Output Calculation

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

from tensorflow.linalg import matmul
from tensorflow.math import exp

import numpy as np

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3

# using Tensorflow 
dense = Dense(units = n_neuron, activation='sigmoid')
y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow) :\n", y_tf.numpy(),'\n')


# calculate with matrix multiplication
z = matmul(X, W) + B
y_man_matmul = 1 / (1 + exp(-z))

print("Y(with matrix multiplication :\n", y_man_matmul.numpy(),'\n')


# calculate with dot product
y_man_vec = np.zeros(shape=(N, n_neuron))

for x_idx in range(N):
  x = X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x*w) + b
    a = 1 / (1 + np.exp(-z))
    y_man_vec[x_idx, nu_idx] = a
  
print("Y(with dot product) :\n ", y_man_vec)

Y(Tensorflow) :
 [[0.7293269  0.7989491  0.16486856]
 [0.45242098 0.55908656 0.49813712]
 [0.35565364 0.3043116  0.18735793]
 [0.12714782 0.6801374  0.6489313 ]] 

Y(with matrix multiplication :
 [[0.72932684 0.7989491  0.16486856]
 [0.45242098 0.5590865  0.49813718]
 [0.35565367 0.3043116  0.18735793]
 [0.12714781 0.68013734 0.6489314 ]] 

Y(with dot product) :
  [[0.72932693 0.79894912 0.16486856]
 [0.45242096 0.55908656 0.49813711]
 [0.35565366 0.3043116  0.18735791]
 [0.12714781 0.68013738 0.64893137]]
