# 2-2 : Cascaded Dense Layer

## Code 2-2-1: Shapes of Cascaded Dense Layers

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape=(N, n_feature))

n_neuron = [3, 5]

dense1 = Dense(units=n_neuron[0], activation='sigmoid')
dense2 = Dense(units=n_neuron[1], activation='sigmoid')

# forward propagation
A1 = dense1(x)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X :{}\n ".format(x.shape))

print("W1 :{}".format(W1.shape))
print("B1: {}".format(B1.shape))
print("A1: {}\n".format(A1.shape))

print("W2 :{}".format(W2.shape))
print("B2: {}".format(B2.shape))
print("Y: {}\n".format(Y.shape))

X :(4, 10)
 
W1 :(10, 3)
B1: (3,)
A1: (4, 3)

W2 :(3, 5)
B2: (5,)
Y: (4, 5)



## Code 2-2-2: Dense Layers with Python List

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='sigmoid')
  dense_layers.append(dense)

print("Input: ", x.shape)

for dense_idx, dense in enumerate(dense_layers):
  x = dense(x)
  print("After dense layer: ", dense_idx+1)
  print(x.shape)

Input:  (4, 10)
After dense layer:  1
(4, 10)
After dense layer:  2
(4, 20)
After dense layer:  3
(4, 30)
After dense layer:  4
(4, 40)
After dense layer:  5
(4, 50)


## Code 2-2-3: Output Calculations

In [17]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.math import exp
from tensorflow.linalg import matmul

N, n_feature = 4, 10
x = tf.random.normal(shape=(N, n_feature))
x_cp = tf.identity(x)

n_neurons = [3, 4, 5]

# using tensorflow
dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='sigmoid')
  dense_layers.append(dense)
print("Input X: ", x.shape,'\n')

W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  x = dense(x)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)
print("Y(Tensorflow): ", x.numpy())

# forward propagation
for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  x_cp = matmul(x_cp, w) + b
  x_cp = 1 / (1 + exp(-x_cp))
print("Y(Manual): ", x_cp.numpy())

Input X:  (4, 10) 

Y(Tensorflow):  [[0.4234627  0.6145655  0.58743477 0.5641475  0.35225004]
 [0.43085963 0.5993666  0.5751444  0.57525396 0.34959346]
 [0.42471507 0.61360663 0.5854598  0.5667886  0.35102612]
 [0.44085532 0.58634454 0.5599884  0.6034602  0.32714677]]
Y(Manual):  [[0.4234627  0.61456555 0.58743477 0.56414753 0.35225   ]
 [0.4308596  0.5993666  0.5751444  0.57525396 0.34959346]
 [0.42471504 0.61360663 0.5854598  0.5667887  0.3510261 ]
 [0.44085535 0.58634454 0.5599884  0.60346025 0.32714677]]
