# 3-4: Softmax Layers

## Code 3-4-1: IO of Softmax

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logits = tf.random.uniform(shape=(2,5), minval=-10, maxval=10)

softmax_value = Activation('softmax')(logits)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)

print("Logits: \n", logits.numpy())
print("Probabilities: \n", softmax_value.numpy())
print("Sum of softmax values:\n", softmax_sum)

Logits: 
 [[ 4.868641   -6.2344456   9.616913    6.055414   -2.2467446 ]
 [ 8.314688   -0.25631905  3.4661484   3.7424774   8.932476  ]]
Probabilities: 
 [[8.3568692e-03 1.2590252e-07 9.6425503e-01 2.7381215e-02 6.7900219e-06]
 [3.4804571e-01 6.5962238e-05 2.7286159e-03 3.5970842e-03 6.4556259e-01]]
Sum of softmax values:
 tf.Tensor([1.         0.99999994], shape=(2,), dtype=float32)


## Code 3-4-2: Softmax in Dense Layers

In [11]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

logits = tf.random.uniform(shape=(8,5), minval=-10, maxval=10)
dense = Dense(units=8, activation='softmax')  # 8개의 구분 클래스

Y = dense(logits)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1.], shape=(8,), dtype=float32)


# 3-5: Multi-class Classifiers

## Code 3-5-1: Multi-class Classifiers

In [15]:
import tensorflow as tf

from tensorflow.keras.models import Model 
from tensorflow.keras.layers import Dense

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=8, activation='relu')
    self.dense2 = Dense(units=5, activation='relu')
    self.dense3 = Dense(units=3, activation='softmax')

  def call(self, x):
    print('X: {}\n{}\n'.format(x.shape, x.numpy()))

    x = self.dense1(x)
    print("A1: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense2(x)
    print("A2: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense3(x)
    print("Y: {}\n{}\n".format(x.shape, x.numpy()))
    print("Sum of vectors: {}\n".format(tf.reduce_sum(x, axis=1)))
    return x
  
model = TestModel()

X = tf.random.uniform(shape=(8,5), minval=-10, maxval=10)
Y = model(X)

X: (8, 5)
[[-8.210411   -1.8284845   1.0131645  -5.628226    6.8358955 ]
 [ 2.5273209  -5.832863    0.32456398 -6.9314623  -1.518712  ]
 [-1.26754     8.288996    1.2097025   5.5350704   0.7957382 ]
 [-7.533214   -7.5521684   1.4748001  -3.759222   -4.853921  ]
 [ 7.697199   -2.0484781   3.5231476   6.478794    9.78256   ]
 [ 2.1079302  -6.485846   -1.9389706   8.059937   -5.967691  ]
 [ 1.6930723   2.673068    1.8105431  -4.0161347   6.177784  ]
 [ 7.156292   -2.703321   -2.720294   -5.878961   -3.6784363 ]]

A1: (8, 8)
[[ 0.          0.          0.52916527  4.5570073   5.412002    3.8847811
   0.          0.        ]
 [ 0.          1.3819759   1.5209116   0.          2.7560325   1.5338314
   5.0450845   1.1234481 ]
 [ 1.0304854   2.5623171   0.          3.6177676   0.          0.
   0.          0.        ]
 [ 4.4394      0.          6.9999433   0.          0.          4.4863634
   0.          0.        ]
 [ 0.          0.          0.          3.4080195   0.          0.
   3.3911788  