# 5-1: Conv Layers

## Code 5-1-1: Shapes of Conv Layers

In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 5
n_filter = 10
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N,n_H,n_W,n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)

W, B = conv.get_weights()

print("image shape: ",images.shape)
print("W shape: ", W.shape)
print("B shape: ", B.shape)
print("y shape: ", y.shape)

image shape:  (1, 28, 28, 5)
W shape:  (3, 3, 5, 10)
B shape:  (10,)
y shape:  (1, 26, 26, 10)


## Code 5-1-2: Correlation Calculation

In [13]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N,n_H, n_W, n_C)))
conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print('Y(Tensorflow): \n', y.numpy().squeeze())

W, B = conv.get_weights()

### calculate in manual ###
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i:i+k_size, j:j+k_size]
    y_man[i,j] = np.sum(window*W) + B

print("Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[ 0.45734084 -0.360254    0.01342472]
 [-0.26148406  0.5353159   0.05475243]
 [ 0.2968904  -0.11175337 -0.24296719]]
Y(Manual): 
 [[ 0.45734084 -0.36025399  0.01342472]
 [-0.26148409  0.53531587  0.05475243]
 [ 0.29689041 -0.11175339 -0.24296725]]


## Code 5-1-3: Correlation with n-channel

In [16]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))
conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print("Y(Tensorflow): \n", y.numpy().squeeze())
W, B = conv.get_weights()

#### Calculate Corr with n-channel in manual
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_H - k_size + 1):
    window = images[i : i+k_size, j : j+k_size, : 1]  # the only difference
    y_man[i, j] = np.sum(window*W) + B

print("Y(Manual): \n", y_man )


Y(Tensorflow): 
 [[-0.127953   -1.3946536  -0.41860986]
 [-0.13747576 -1.1003485  -0.72896576]
 [-0.8146044  -0.34316075 -0.79812586]]
Y(Manual): 
 [[-0.59832114 -0.70946652 -0.03840876]
 [-0.40151644 -0.56990868 -0.62933594]
 [-0.47082669 -0.40049458 -0.96005833]]
