# 5-2: Conv Layer with Filters

## Code 5-2-1: Shapes with Filters

In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))
conv = Conv2D(filters = n_filter, kernel_size = k_size)

Y = conv(images)

W, B = conv.get_weights()

print("Input Image: {}".format(images.shape))
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))

Input Image: (32, 28, 28, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Image: (32, 26, 26, 5)


## Code 5-2-2: Computations with Filters

In [15]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze() ,(2,0,1))
print("Y(Tensorflow): \n", Y)

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:,:,:, c]
  c_b = B[c]

  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w + k_size, :]
      conv = np.sum(window * c_W) + c_b

      Y_man[h, w, c] = conv

print("Y(Manual): \n", np.transpose(Y_man, (2, 0, 1)))

Y(Tensorflow): 
 [[[ 1.0906558   1.280765  ]
  [ 0.87172484  0.9914582 ]]

 [[-0.7205338  -1.1076542 ]
  [-0.03515377 -0.42661795]]

 [[-0.53797144 -0.317673  ]
  [-0.75700486 -0.55726874]]]
Y(Manual): 
 [[[ 1.0906558   1.2807653 ]
  [ 0.87172484  0.99145824]]

 [[-0.72053373 -1.10765433]
  [-0.03515376 -0.42661798]]

 [[-0.53797156 -0.31767303]
  [-0.75700474 -0.55726868]]]


# 5-3: Conv Layers with Activation Functions

## Code 5-3-1: Conv Layers with Activation Functions

In [19]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size, activation='sigmoid')
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze() ,(2,0,1))
print("Y(Tensorflow): \n", Y)

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  c_W = W[:,:,:, c]
  c_b = B[c]

  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w + k_size, :]
      conv = np.sum(window * c_W) + c_b
      conv = 1 / (1 + np.exp(-conv))

      Y_man[h, w, c] = conv

print("Y(Manual): \n", np.transpose(Y_man, (2, 0, 1)))

Y(Tensorflow): 
 [[[0.5861047  0.57133895]
  [0.48506573 0.5149525 ]]

 [[0.6694008  0.67246807]
  [0.6473954  0.715398  ]]

 [[0.42181945 0.43952766]
  [0.4507804  0.4056277 ]]]
Y(Manual): 
 [[[0.58610472 0.57133892]
  [0.48506574 0.51495247]]

 [[0.66940081 0.67246805]
  [0.64739537 0.715398  ]]

 [[0.42181942 0.43952767]
  [0.45078042 0.40562776]]]
