# 6-1: Max/Avg Pooling

## Code 6-1-1: Max Pooling

In [6]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D\

L, f, s = 10, 2, 1  

x = tf.random.normal(shape=(1, L, 1))
pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled max(tf): {}\n{}".format(pooled_max.shape,
                                      pooled_max.numpy().flatten()))

# calculate in Manual

x = x.numpy().flatten()
pooled_max_man = np.zeros(shape=(L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i] = np.max(window)

print("pooled max(manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_man))

x: (1, 10, 1)
[ 0.07675932 -0.05307147 -0.7452988   1.7960348  -0.03585016 -1.4751439
 -0.47944736 -1.7702109  -0.36167753  2.2999728 ]
pooled max(tf): (1, 9, 1)
[ 0.07675932 -0.05307147  1.7960348   1.7960348  -0.03585016 -0.47944736
 -0.47944736 -0.36167753  2.2999728 ]
pooled max(manual): (9,)
[ 0.07675932 -0.05307147  1.79603481  1.79603481 -0.03585016 -0.47944736
 -0.47944736 -0.36167753  2.29997277]


## Code 6-1-2: Average Pooling

In [9]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print(f"x: {x.shape}\n{x.numpy().flatten()}")
print(f"pooled_avg(tf): {pooled_avg.shape}\n{pooled_avg.numpy().flatten()}")

# calculate in manual
x = x.numpy().flatten()
pooled_avg_man = np.zeros(shape=(L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_avg_man[i] = np.mean(window)

print("pooled avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                         pooled_avg_man))

x: (1, 10, 1)
[ 0.15697572  0.42421332  1.3468908  -1.7024887   1.546545   -0.89794415
  1.0132765   1.3978297   0.04160708 -0.65770286]
pooled_avg(tf): (1, 9, 1)
[ 0.29059452  0.88555205 -0.17779893 -0.07797182  0.32430044  0.05766615
  1.205553    0.71971834 -0.3080479 ]
pooled avg(Manual): (9,)
[ 0.29059452  0.88555205 -0.17779893 -0.07797182  0.32430044  0.05766615
  1.20555305  0.71971834 -0.30804789]


# 6-2: 2D Max/Avg Pooling

## 6-2-1: 2D Max Pooling

In [12]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print(f"x: {x.shape}\n{x.numpy().squeeze()}")
print(f"pooled_max(tf): {pooled_max.shape}\n{pooled_max.numpy().squeeze()}")

# calculate in manual
x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j] = np.max(window)

print("pooled max(manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_man))

x: (1, 5, 5, 1)
[[-0.8266549  -1.9707      0.05982965 -0.34653372 -1.6274109 ]
 [ 0.48443273 -0.74323905 -0.97055614  0.8687337  -0.47625443]
 [-0.0295627   0.8688091  -0.34027386 -0.45929784 -0.44085348]
 [ 1.693047   -0.16567189 -1.4028362  -0.07336625 -1.2610399 ]
 [-0.6697208   1.2737207   1.2060729   0.29360965  0.48286685]]
pooled_max(tf): (1, 4, 4, 1)
[[ 0.48443273  0.05982965  0.8687337   0.8687337 ]
 [ 0.8688091   0.8688091   0.8687337   0.8687337 ]
 [ 1.693047    0.8688091  -0.07336625 -0.07336625]
 [ 1.693047    1.2737207   1.2060729   0.48286685]]
pooled max(manual): (4, 4)
[[ 0.48443273  0.05982965  0.8687337   0.8687337 ]
 [ 0.8688091   0.8688091   0.8687337   0.8687337 ]
 [ 1.69304705  0.8688091  -0.07336625 -0.07336625]
 [ 1.69304705  1.27372074  1.20607293  0.48286685]]


## 6-2-2: 2D Avg Pooling

In [20]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print(f"x: {x.shape}\n{x.numpy().squeeze()}")
print(f"pooled_avg(tf): {pooled_avg.shape}\n{pooled_avg.numpy().squeeze()}")

# calculate in manual
x = x.numpy().squeeze()

pooled_avg_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i,j] = np.mean(window)

print("pooled avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                         pooled_avg_man))

x: (1, 5, 5, 1)
[[-0.33066905  0.32648653  0.26721793  0.33764765  1.1462232 ]
 [-0.64298266 -0.00426879 -0.4092675  -0.49842003  0.63318545]
 [-0.59008604  0.9782295  -0.17224367  0.03743836  1.5119944 ]
 [ 0.5167808   0.09174345  2.8773153  -0.01174169  1.4114444 ]
 [-2.7715998  -1.3211397   0.13061766  1.7044449  -1.3713949 ]]
pooled_avg(tf): (1, 4, 4, 1)
[[-0.16285849  0.04504205 -0.07570549  0.4046591 ]
 [-0.06477699  0.09811239 -0.26062322  0.42104954]
 [ 0.24916694  0.94376117  0.6826921   0.7372839 ]
 [-0.8710538   0.44463417  1.175159    0.4331882 ]]
pooled avg(Manual): (4, 4)
[[-0.16285849  0.04504205 -0.07570549  0.40465909]
 [-0.06477699  0.09811239 -0.26062322  0.42104954]
 [ 0.24916694  0.94376117  0.68269211  0.73728389]
 [-0.87105381  0.44463417  1.17515898  0.4331882 ]]
