# 6-3: 3D Max/Avg Pooling

## Code 6-3-1: 3D Max Pooling

In [6]:
import math
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2, 2

x = tf.random.normal(shape=(N, n_H, n_W, n_C ))
print("x: {}\n{}\n".format(x.shape,
                         np.transpose(x.numpy().squeeze(), (2,0,1))))

pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2,0,1))
print("pooled max(tf): {}\n{}\n".format(pooled_max.shape,
                                        pooled_max_t))

# calculate in manual
x = x.numpy().squeeze()
n_H_ = math.floor((n_H - f)/s + 1)
n_W_ = math.floor((n_W - f)/s + 1)
pooled_max_man = np.zeros(shape=(n_H_, n_W_, n_C))

for c in range(n_C):
  c_image = x[:,:,c]
   
  h_ = 0 
  for h in range(0, n_H - f + 1, s):
    w_ = 0
    for w in range(0, n_H - f + 1, s):
      window = c_image[h:h+f, w:w+f]
      pooled_max_man[h_, w_, c] = np.max(window)

      w_ += 1
    h_ += 1

pooled_max_t = np.transpose(pooled_max_man, (2,0,1))
print("pooled max(manual): {}\n{}".format(pooled_max_t.shape,
                                          pooled_max_t))

x: (1, 5, 5, 3)
[[[-0.14075273  0.15508655  0.6702597  -0.18053013  0.23867553]
  [-0.4256967  -0.61594963 -0.94763726 -0.11131188  0.9403567 ]
  [ 0.54142976  1.4874392   2.267933   -1.507744   -0.1661761 ]
  [ 0.97064024 -1.1084088   0.34651113 -0.8881678   0.09293788]
  [-0.8013011   0.50812745 -0.03628084  0.15340267 -0.23938662]]

 [[ 1.2814499  -0.66005135  0.7444615  -1.6707152  -1.1608502 ]
  [-1.1676228  -0.08493025  0.28009036 -0.4133136  -1.0201732 ]
  [ 0.08732023  0.6485989  -0.06999384 -0.73251903 -0.77205586]
  [-1.4757161  -0.8870986  -0.27418968 -1.8324361   0.80452514]
  [ 0.23188254  1.7599074   2.2559142   2.1205912   1.1914957 ]]

 [[ 1.5188518   1.1349068   0.76832795  0.8290511   1.1344664 ]
  [-0.03226722  0.10577284 -0.6312035   0.46876562  1.0212446 ]
  [-1.3398472  -0.44458026 -0.14505808 -1.2140836   0.41815102]
  [-1.2979126  -0.74119306 -1.8283244   0.60163534  0.2332008 ]
  [ 1.1534152  -0.725698    0.17662375 -1.8171546   0.48522195]]]

pooled max(tf): (

# 6-4: Padding

## Code 6-4-1: Zero Padding2D Layer

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape=(1,3,3,3))
print(np.transpose(images.numpy().squeeze(), (2,0,1)))
print('=====zero padding====')

zero_padding = ZeroPadding2D(padding=1)
y = zero_padding(images)

print(np.transpose(y.numpy().squeeze(), (2, 0 ,1)))

[[[ 0.45160654  0.55942774  1.0552562 ]
  [-0.6023064   0.62787485 -0.38395938]
  [-0.2970826   0.24323909 -0.9061243 ]]

 [[ 0.54222506  0.7751591   0.9365496 ]
  [ 0.6230268  -0.7335661  -0.53296673]
  [-1.5485706  -0.92681575  1.2700521 ]]

 [[-2.2914324   0.2987331   0.01300878]
  [ 1.2023929  -1.8073341  -1.0153126 ]
  [-0.23390688  1.060542   -0.6687182 ]]]
=====zero padding====
[[[ 0.          0.          0.          0.          0.        ]
  [ 0.          0.45160654  0.55942774  1.0552562   0.        ]
  [ 0.         -0.6023064   0.62787485 -0.38395938  0.        ]
  [ 0.         -0.2970826   0.24323909 -0.9061243   0.        ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.          0.        ]
  [ 0.          0.54222506  0.7751591   0.9365496   0.        ]
  [ 0.          0.6230268  -0.7335661  -0.53296673  0.        ]
  [ 0.         -1.5485706  -0.92681575  1.2700521   0.        ]
  [ 0.          0.          0.    

## Code 6-4-2: Zero Padding with Conv2D Layers

In [14]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding='same')
y = conv(images)

print(y.shape)

(1, 28, 28, 1)


# 6-5: Strides

## Code 6-5-1: Strides in **Conv2D** Layers

In [15]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding='valid', strides=2)
y = conv(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 1)


## Code 6-5-2: Strides in **Pooling** Layers

In [17]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape=(1, 28, 28, 3))
pool = MaxPooling2D(pool_size=3, strides=2)
y = pool(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)


stride를 적용하면 h,w 가 pooling layer나 conv layer 결과가 동일하다